apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 4
  selector:
    matchLabels:
      run: my-app
  template:
    metadata:
      labels: 
        run: my-app
    spec:
      containers: 
      - name: my-app
        image: anaisurlichs/react-article-display:master
        ports: 
        - containerPort: 80
        imagePullPolicy: Always


